name: Deploy to Cloudflare

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:cf

      - name: Deploy to Cloudflare Workers with Wrangler
        id: deploy-production
        uses: cloudflare/wrangler-action@v3.14.1
        # deploying to production
        if: github.event_name != 'pull_request'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Workers with Wrangler
        id: deploy-preview
        uses: cloudflare/wrangler-action@v3.14.1
        # deploying to preview
        if: github.event_name == 'pull_request'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload
